INSERT INTO Movies (id, title, released, tagline) VALUES
('TheMatrix', 'The Matrix', 1999, 'Welcome to the Real World'),
('TheMatrixReloaded', 'The Matrix Reloaded', 2003, 'Free your mind'),
('TheMatrixRevolutions', 'The Matrix Revolutions', 2003, 'Everything that has a beginning has an end'),
('TheDevilsAdvocate', 'The Devils Advocate', 1997, 'Evil has its winning ways'),
('AFewGoodMen', 'A Few Good Men', 1992, 'In the heart of the nations capital, in a courthouse of the U.S. government, one man will stop at nothing to keep his honor, and one will stop at nothing to find the truth.'),
('TopGun', 'Top Gun', 1986, 'I feel the need, the need for speed.'),
('JerryMaguire', 'Jerry Maguire', 2000, 'The rest of his life begins now.'),
('StandByMe', 'Stand By Me', 1986, 'For some, its the last real taste of innocence, and the first real taste of life. But for everyone, its the time that memories are made of.'),
('AsGoodAsItGets', 'As Good as It Gets', 1997, 'A comedy from the heart that goes for the throat.'),
('WhatDreamsMayCome', 'What Dreams May Come', 1998, 'After life there is more. The end is just the beginning.'),
('SnowFallingonCedars', 'Snow Falling on Cedars', 1999, 'First loves last. Forever.'),
('YouveGotMail', 'Youve Got Mail', 1998, 'At odds in life... in love on-line.'),
('SleeplessInSeattle', 'Sleepless in Seattle', 1993, 'What if someone you never met, someone you never saw, someone you never knew was the only someone for you?'),
('JoeVersustheVolcano', 'Joe Versus the Volcano', 1990, 'A story of love, lava and burning desire.'),
('WhenHarryMetSally', 'When Harry Met Sally', 1998, 'At odds in life... in love on-line.'),
('ThatThingYouDo', 'That Thing You Do', 1996, 'In every life there comes a time when that thing you dream becomes that thing you do'),
('TheReplacements', 'The Replacements', 2000, 'Pain heals, Chicks dig scars... Glory lasts forever'),
('RescueDawn', 'RescueDawn', 2006, 'Based on the extraordinary true story of one mans fight for freedom'),
('TheBirdcage', 'The Birdcage', 1996, 'Come as you are'),
('Unforgiven', 'Unforgiven', 1992, 'Its a hell of a thing, killing a man'),
('JohnnyMnemonic', 'Johnny Mnemonic', 1995, 'The hottest data on earth. In the coolest head in town'),
('CloudAtlas', 'Cloud Atlas', 2012, 'Everything is connected'),
('TheDaVinciCode', 'The Da Vinci Code', 2006, 'Break The Codes'),
('VforVendetta', 'V for Vendetta', 2006, 'Freedom! Forever!'),
('SpeedRacer', 'Speed Racer', 2008, 'Speed has no limits'),
('NinjaAssassin', 'Ninja Assassin', 2009, 'Prepare to enter a secret world of assassins'),
('TheGreenMile', 'The Green Mile', 1999, 'Walk a mile youll never forget.'),
('FrostNixon', 'Frost/Nixon', 2008, '400 million people were waiting for the truth.'),
('Hoffa', 'Hoffa', 1992, 'He didnt want law. He wanted justice.'),
('Apollo13', 'Apollo 13', 1995, 'Houston, we have a problem.'),
('Twister', 'Twister', 1996, 'Dont Breathe. Dont Look Back.'),
('CastAway', 'Cast Away', 2000, 'At the edge of the world, his journey begins.'),
('OneFlewOvertheCuckoosNest', 'One Flew Over the Cuckoos Nest', 1975, 'If hes crazy, what does that make you?'),
('SomethingsGottaGive', 'Somethings Gotta Give', 2003, 'An annoying movie'),
('BicentennialMan', 'Bicentennial Man', 1999, 'One robots 200 year journey to become an ordinary man.'),
('CharlieWilsonsWar', 'Charlie Wilsons War', 2007, 'A stiff drink. A little mascara. A lot of nerve. Who said they couldnt bring down the Soviet empire.'),
('ThePolarExpress', 'The Polar Express', 2004, 'This Holiday Season… Believe'),
('ALeagueofTheirOwn', 'A League of Their Own', 1992, 'Once in a lifetime you get a chance to do something different.');