
DROP TABLE IF EXISTS Acted_In CASCADE;
CREATE TABLE Directed (
  movie_id VARCHAR(255) REFERENCES Movies(id),
  person_id VARCHAR(255) REFERENCES Persons(id),
  PRIMARY KEY (movie_id, person_id)
);


INSERT INTO Acted_In (movie_id, person_id) VALUES
('TheMatrix', 'AndyW'),
('TheMatrix', 'LanaW'),
('TheMatrixReloaded', 'AndyW'),
('TheMatrixReloaded', 'LanaW'),
('TheMatrixRevolutions', 'AndyW'),
('TheMatrixRevolutions', 'LanaW'),
('TheDevilsAdvocate', 'Taylor'),
('AFewGoodMen', 'RobR'),
('TopGun', 'TonyS'),
('JerryMaguire', 'CameronC'),
('StandByMe', 'RobR'),
('AsGoodAsItGets', 'JamesB'),
('WhatDreamsMayCome', 'VincentW'),
('SnowFallingonCedars', 'ScottH'),
('YouveGotMail', 'NoraE'),
('SleeplessInSeattle', 'NoraE'),
('JoeVersustheVolcano', 'JohnS'),
('WhenHarryMetSally', 'RobR'),
('ThatThingYouDo', 'TomH'),
('TheReplacements', 'Howard'),
('RescueDawn', 'WernerH'),
('TheBirdcage', 'MikeN'),
('Unforgiven', 'ClintE'),
('JohnnyMnemonic', 'RobertL'),
('CloudAtlas', 'TomT'),
('CloudAtlas', 'AndyW'),
('CloudAtlas', 'LanaW'),
('TheDaVinciCode', 'RonH'),
('VforVendetta', 'JamesM'),
('SpeedRacer', 'AndyW'),
('SpeedRacer', 'LanaW'),
('NinjaAssassin', 'JamesM'),
('TheGreenMile', 'FrankD'),
('FrostNixon', 'RonH'),
('Hoffa', 'DannyD'),
('Apollo13', 'RonH'),
('Twister', 'JanB'),
('CastAway', 'RobertZ'),
('OneFlewOvertheCuckoosNest', 'MilosF'),
('SomethingsGottaGive', 'NancyM'),
('BicentennialMan', 'ChrisC'),
('CharlieWilsonsWar', 'MikeN'),
('ThePolarExpress', 'RobertZ'),
('ALeagueofTheirOwn', 'PennyM');